version: '3'

services:
  magicmirror:
    image: karsten13/magicmirror:latest
    container_name: magicmirror
    restart: unless-stopped
    volumes:
      # Customisation - only mount the files under source control, not entire dirs
      # \-> CSS
      - ./magicmirror/css/custom.css:/opt/magic_mirror/css/custom.css
      # \-> modules
      - ./magicmirror/modules/MMM-OnThisDay:/opt/magic_mirror/modules/MMM-OnThisDay
      - ./magicmirror/modules/MMM-QRCode:/opt/magic_mirror/modules/MMM-QRCode
      - ./magicmirror/modules/MMM-Sonos:/opt/magic_mirror/modules/MMM-Sonos
      # Bind system files and folders
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /opt/vc:/opt/vc/:ro
      - /usr/bin/vcgencmd:/usr/bin/vcgencmd
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    devices:
      - /dev/vchiq
    environment:
      LD_LIBRARY_PATH: /opt/vc/lib
      DISPLAY: unix:0.0
    network_mode: host
    shm_size: "128mb"
    command:
      - npm
      - run
      - start
